#test-multiple-and-conditionnals.yaml

---

- name: "and conditionnals"
  hosts: localhost
  gather_facts: True
  tasks:
    - name: "Test two conditions in one line"
      debug:
        msg: "{{ ansible_hostname }} Ubuntu 22"
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "22"
    - name: "Test two conditions in two lines"
      debug:
        msg: "{{ ansible_hostname }} Ubuntu 22"
      when: ansible_distribution == "Ubuntu" and
            ansible_distribution_major_version == "22"
    - name: "Test multiple conditions in a list"
      debug:
        msg: "{{ ansible_hostname }} Ubuntu 22"
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_major_version == "22"