---
# play which gives the uid of the new user
- name: Calculate UID
  hosts: projet5
  tasks:
  - name: Get all users info
    getent:
      database: passwd
      split: ":"
  - name: Create a list of uid
    set_fact:
      unique_list: "{{ (unique_list | default([]) + [item]) | unique | map('int')}}"
    loop: "{{ getent_passwd | dict2items | map(attribute='value') | map(attribute='1') }}"
  - name: Get greater value from the list
    set_fact:
      result: "{{ unique_list | reject('ge', 3999) | list | max }}"
  - name: Print the value
    debug:
      msg: "The index of the greatest number in the list is {{ result }}"