---
# tasks file for newrole

- name: be sure apache is installed
  hosts: nodes
  tasks:
    - name: apache
      apt:
        name: apache2
        state: present
      tags: apache

    - name: be sure apache is configured
      template:
        src: ../files/apache2.conf
        dest: /etc/apache2/apache2.conf
      tags: apache
      notify: Restart apache

    - name: be sure apache2 is running and enabled
      systemd_service:
        name: apache2
        state: started
        enabled: yes
  handlers:
    - name: Restart apache
      systemd_service:
        name: apache2
        state: restarted